# Generated by Django 2.2.17 on 2020-12-28 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_customer', models.IntegerField(verbose_name='今天新增客户数量')),
                ('day_liaison', models.IntegerField(verbose_name='今天新增联系人数量')),
                ('day_record', models.IntegerField(verbose_name='今天新增拜访记录数量')),
                ('day_business', models.IntegerField(verbose_name='今天新增商机数量')),
                ('mouth_customer', models.IntegerField(verbose_name='本月新增客户数量')),
                ('mouth_liaison', models.IntegerField(verbose_name='本月新增联系人数量')),
                ('mouth_record', models.IntegerField(verbose_name='本月新增拜访记录数量')),
                ('mouth_business', models.IntegerField(verbose_name='本月新增商机数量')),
                ('all_customer', models.IntegerField(verbose_name='全部客户数量')),
                ('all_liaison', models.IntegerField(verbose_name='全部联系人数量')),
                ('all_record', models.IntegerField(verbose_name='全部拜访记录数量')),
                ('all_business', models.IntegerField(verbose_name='全部商机数量')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户数据统计',
                'verbose_name_plural': '用户数据统计',
                'db_table': 'user_count',
            },
        ),
    ]
