# Generated by Django 2.2.17 on 2020-12-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercount',
            name='all_business',
            field=models.IntegerField(default=0, verbose_name='全部商机数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='all_customer',
            field=models.IntegerField(default=0, verbose_name='全部客户数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='all_liaison',
            field=models.IntegerField(default=0, verbose_name='全部联系人数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='all_record',
            field=models.IntegerField(default=0, verbose_name='全部拜访记录数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='day_business',
            field=models.IntegerField(default=0, verbose_name='今天新增商机数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='day_customer',
            field=models.IntegerField(default=0, verbose_name='今天新增客户数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='day_liaison',
            field=models.IntegerField(default=0, verbose_name='今天新增联系人数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='day_record',
            field=models.IntegerField(default=0, verbose_name='今天新增拜访记录数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='mouth_business',
            field=models.IntegerField(default=0, verbose_name='本月新增商机数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='mouth_customer',
            field=models.IntegerField(default=0, verbose_name='本月新增客户数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='mouth_liaison',
            field=models.IntegerField(default=0, verbose_name='本月新增联系人数量'),
        ),
        migrations.AlterField(
            model_name='usercount',
            name='mouth_record',
            field=models.IntegerField(default=0, verbose_name='本月新增拜访记录数量'),
        ),
    ]
