# Generated by Django 2.2.17 on 2020-12-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201228_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='日期')),
                ('month', models.IntegerField(verbose_name='月份')),
            ],
            options={
                'verbose_name': '日期表',
                'verbose_name_plural': '日期表',
                'db_table': 'date',
            },
        ),
    ]
