# Generated by Django 2.2.17 on 2021-03-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='day_record',
            field=models.IntegerField(default=0, verbose_name='昨天拜访记录数量'),
        ),
    ]
