# Generated by Django 2.2.17 on 2021-03-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210303_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='all_business',
        ),
        migrations.RemoveField(
            model_name='count',
            name='all_liaison',
        ),
        migrations.RemoveField(
            model_name='count',
            name='all_record',
        ),
        migrations.RemoveField(
            model_name='count',
            name='day_business',
        ),
        migrations.RemoveField(
            model_name='count',
            name='day_customer',
        ),
        migrations.RemoveField(
            model_name='count',
            name='day_liaison',
        ),
        migrations.RemoveField(
            model_name='count',
            name='day_record',
        ),
        migrations.RemoveField(
            model_name='count',
            name='month_business',
        ),
        migrations.RemoveField(
            model_name='count',
            name='month_customer',
        ),
        migrations.RemoveField(
            model_name='count',
            name='month_liaison',
        ),
        migrations.RemoveField(
            model_name='count',
            name='month_record',
        ),
        migrations.AddField(
            model_name='count',
            name='finish_business',
            field=models.IntegerField(default=0, verbose_name='完成商机'),
        ),
        migrations.AddField(
            model_name='count',
            name='follow_business',
            field=models.IntegerField(default=0, verbose_name='跟进商机'),
        ),
        migrations.AddField(
            model_name='count',
            name='new_business',
            field=models.IntegerField(default=0, verbose_name='新增商机'),
        ),
        migrations.AddField(
            model_name='count',
            name='new_customer',
            field=models.IntegerField(default=0, verbose_name='新增客户'),
        ),
        migrations.AddField(
            model_name='count',
            name='week_business',
            field=models.IntegerField(default=0, verbose_name='本周商机数量'),
        ),
        migrations.AddField(
            model_name='count',
            name='week_phone',
            field=models.IntegerField(default=0, verbose_name='本周外呼数量'),
        ),
        migrations.AddField(
            model_name='count',
            name='week_record',
            field=models.IntegerField(default=0, verbose_name='本周拜访数量'),
        ),
        migrations.AddField(
            model_name='count',
            name='yesterday_phone',
            field=models.IntegerField(default=0, verbose_name='昨日外呼数量'),
        ),
        migrations.AddField(
            model_name='count',
            name='yesterday_record',
            field=models.IntegerField(default=0, verbose_name='昨日拜访记录'),
        ),
    ]
