# Generated by Django 2.2.17 on 2021-03-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210315_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='up_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User', verbose_name='上级主管'),
        ),
    ]
