# Generated by Django 2.2.17 on 2020-12-21 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='客户名称')),
                ('rank', models.SmallIntegerField(choices=[(1, '重点客户'), (2, '一般客户'), (3, '普通客户')], default=1, verbose_name='客户级别')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户网址')),
                ('scale', models.SmallIntegerField(blank=True, choices=[(1, '0~10人'), (2, '10~50人'), (3, '50~100人'), (4, '100~1000人'), (5, '1000人及以上')], default=1, null=True, verbose_name='客户规模')),
                ('nature', models.SmallIntegerField(blank=True, choices=[(8, '有限责任公司'), (9, '股份有限公司'), (1, '国有企业'), (2, '集体企业'), (3, '私营企业'), (4, '个体工商户'), (5, '合伙企业'), (6, '联营企业'), (7, '股份合作制企业')], default=8, null=True, verbose_name='客户性质')),
                ('industry', models.SmallIntegerField(blank=True, choices=[(1, '机台设备制造商'), (2, '生产制造型企业'), (3, '系统集成商'), (4, '分销商'), (5, '其它')], default=1, null=True, verbose_name='客户行业')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户备注')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_province', models.CharField(blank=True, max_length=32, null=True, verbose_name='收货省份')),
                ('shop_city', models.CharField(blank=True, max_length=32, null=True, verbose_name='收货市区')),
                ('shop_area', models.CharField(blank=True, max_length=32, null=True, verbose_name='收货区域')),
                ('shop_town', models.CharField(blank=True, max_length=32, null=True, verbose_name='收货街道')),
                ('shop_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='收货详细地址')),
                ('shop_username', models.CharField(blank=True, max_length=32, null=True, verbose_name='收货地收货人')),
                ('shop_phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='收货收货人电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shop', to='customer.Customer', verbose_name='客户名称')),
            ],
            options={
                'verbose_name': '客户收货地址信息',
                'verbose_name_plural': '客户收货地址信息',
                'db_table': 'customer_shop',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_province', models.CharField(blank=True, max_length=32, null=True, verbose_name='发票省份')),
                ('invoice_city', models.CharField(blank=True, max_length=32, null=True, verbose_name='发票市区')),
                ('invoice_area', models.CharField(blank=True, max_length=32, null=True, verbose_name='发票区域')),
                ('invoice_town', models.CharField(blank=True, max_length=32, null=True, verbose_name='发票街道')),
                ('invoice_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='发票详细地址')),
                ('invoice_username', models.CharField(blank=True, max_length=32, null=True, verbose_name='发票地收货人')),
                ('invoice_phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='发票收货人电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoice', to='customer.Customer', verbose_name='客户名称')),
            ],
            options={
                'verbose_name': '客户发票地址信息',
                'verbose_name_plural': '客户发票地址信息',
                'db_table': 'customer_invoice',
                'ordering': ['-created_at'],
            },
        ),
    ]
