# Generated by Django 2.2.17 on 2021-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0002_auto_20210329_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr',
            name='key1_true',
            field=models.SmallIntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True, verbose_name='完成情况1'),
        ),
        migrations.AlterField(
            model_name='okr',
            name='key2_true',
            field=models.SmallIntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True, verbose_name='完成情况2'),
        ),
        migrations.AlterField(
            model_name='okr',
            name='key3_true',
            field=models.SmallIntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True, verbose_name='完成情况3'),
        ),
    ]
