# Generated by Django 2.2.17 on 2020-12-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_auto_20201225_1038'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商机名称')),
                ('winning_rate', models.SmallIntegerField(choices=[(1, '0%'), (2, '20%'), (3, '50%'), (4, '80%'), (5, '100%')], default=2, verbose_name='赢单率')),
                ('money', models.CharField(blank=True, max_length=16, null=True, verbose_name='预估金额')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='商机备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='商机客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_business', to='users.User', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户商机',
                'verbose_name_plural': '客户商机',
                'db_table': 'business',
            },
        ),
    ]
