# Generated by Django 2.2.17 on 2020-12-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20201228_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': '客户商机', 'verbose_name_plural': '客户商机'},
        ),
    ]
