# Generated by Django 2.2.17 on 2020-12-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('customer', '0002_auto_20201225_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '线上'), (2, '线下')], default=1, verbose_name='客户拜访方式')),
                ('main', models.TextField(blank=True, max_length=1000, null=True, verbose_name='主要事宜')),
                ('next', models.TextField(blank=True, max_length=1000, null=True, verbose_name='后期规划')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='拜访备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_record', to='customer.Customer', verbose_name='客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_record', to='users.User', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户拜访记录',
                'verbose_name_plural': '客户拜访记录',
                'db_table': 'record',
            },
        ),
    ]
