# Generated by Django 2.2.17 on 2020-12-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201225_1038'),
        ('users', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerRecord',
            new_name='Record',
        ),
    ]
