# Generated by Django 2.2.17 on 2020-12-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20201228_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': '客户拜访记录', 'verbose_name_plural': '客户拜访记录'},
        ),
    ]
