# Generated by Django 2.2.17 on 2020-12-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20201228_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at'], 'verbose_name': '客户拜访记录', 'verbose_name_plural': '客户拜访记录'},
        ),
    ]
