# Generated by Django 2.2.17 on 2021-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20201229_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '电联'), (2, '拜访')], default=1, verbose_name='客户拜访方式'),
        ),
    ]
