# Generated by Django 2.2.17 on 2021-03-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_auto_20210310_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '线上'), (2, '线下')], default=1, verbose_name='客户拜访方式'),
        ),
    ]
