# Generated by Django 2.2.17 on 2020-12-25 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('customer', '0002_auto_20201225_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liaison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='联系人姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='联系人电话')),
                ('job', models.SmallIntegerField(choices=[(2, '经理'), (3, '采购'), (4, '技术'), (5, '售后'), (1, '业务'), (6, '其他')], default=1, verbose_name='职称')),
                ('injob', models.SmallIntegerField(choices=[(1, '在职'), (0, '离职')], default=1, verbose_name='是否在职')),
                ('wx', models.CharField(blank=True, max_length=64, null=True, verbose_name='微信')),
                ('qq', models.CharField(blank=True, max_length=64, null=True, verbose_name='QQ')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='电子邮箱')),
                ('hobby', models.CharField(blank=True, max_length=128, null=True, verbose_name='兴趣爱好')),
                ('birthday', models.CharField(blank=True, max_length=64, null=True, verbose_name='生日')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison', to='customer.Customer', verbose_name='客户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaison', to='users.User', verbose_name='创建人')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'db_table': 'liaison',
            },
        ),
    ]
