# Generated by Django 2.2.17 on 2020-12-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liaison', '0003_auto_20201228_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liaison',
            options={'ordering': ['-created_at'], 'verbose_name': '联系人', 'verbose_name_plural': '联系人'},
        ),
    ]
